export const languageData = [
  {
    locale: 'sp',
    translation: {
      Brand: "Marca",
      make_first_reservation: "Haz tu primera reserva",
      home: 'Hogar',
      payment_details: 'Datos de pago',
      no_messages_yet:'Aún no hay mensajes',
      checking_subscription: 'Verificando suscripción...',
      confirm_reservation: 'Confirmar la reserva',
      favorites: 'Favoritos',
      offer: 'Ofrecer',
      messages: 'Mensajes',
      profile: 'Perfil',
      create_your_account: 'Crea tu cuenta',
      first_name: 'Nombre',
      street_and_number: 'Calle y numero',
      street_number_placeholder: 'calle de Pez',
      door: 'Puerta',
      door_placeholder: '1A',
      zip_code: 'Código postal',
      country: 'Pais',
      country_placeholder: 'España',
      email_placeholder: 'email@email.com',
      telephone: 'Teléfono',
      accept_terms: 'Acepto la',
      privacy_policy: 'Política de Privacidad',
      last_name: 'Apellido',
      your_first_name: 'Tu nombre',
      your_last_name: 'Tu apellido',
      email: 'Email',
      your_email: 'Tu email',
      password: 'Contraseña',
      register: 'Registrarme',
      already_have_an_account: '¿Ya tienes una cuenta?',
      dont_have_an_account: '¿No tienes una cuenta?',
      login: 'Iniciar sesión',
      successful_registration: '¡Registro exitoso!',
      register_success_msg:
        'Tu cuenta ha sido creada exitosamente. Ahora podrás explorar y disfrutar de todas las funcionalidades que nuestra app tiene para ofrecer.',
      back_to_top: 'Volver al inicio',
      something_went_wrong: '¡Algo salió mal!',
      forget_password_msg:
        '¿Has olvidado tu contraseña? No te preocupes, te ayudaremos a restablecerla. Ingresa tu correo electrónico asociado a tu cuenta y te enviaremos un enlace para crear una nueva contraseña.',
      register_fail_msg:
        'Parece que hubo un problema al procesar tu registro. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      forget_password: 'He olvidado mi contraseña',
      sign_up: 'Regístrate',
      recover_password: 'Recuperar la contraseña',
      login_fail_msg:
        'Parece que hubo un problema al iniciar la sesión. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      repeat_email: 'Repite tu email',
      send_reset_link: 'Enviar enlace de restablecimiento',
      mail_sent: '¡Correo enviado!',
      link_sent_msg:
        'Hemos enviado un enlace de restablecimiento de contraseña a tu correo electrónico. Por favor, revisa tu bandeja de entrada y sigue las instrucciones para crear una nueva contraseña.',
      reset_password: 'Restablecer la contraseña',
      new_password: 'Nueva contraseña',
      repeat_password: 'Repite la nueva contraseña',
      save_password: 'Guardar la contraseña',
      password_reset: '¡Contraseña restablecida!',
      booking_save: '¡Producto reservado!',
      booking_success_msg:
        'Tu reserva ha sido completada con éxito. El propietario confirmará tu solicitud lo antes posible. Te hemos enviado un correo con todos los detalles.',
      booking_fail_msg:
        'Parece que hubo un problema al reservar el producto. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      password_save_msg:
        'Tu nueva contraseña ha sido guardada con éxito. Ya puedes usar tu nueva contraseña para iniciar sesión en tu cuenta.',
      password_save_fail_msg:
        'Parece que hubo un problema al guardar tu contraseña. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      first_name_required: 'El nombre es obligatorio',
      last_name_required: 'El apellido es obligatorio',
      invalid_email: 'Dirección de correo electrónico no válida',
      password_min_length: 'La contraseña debe tener al menos 6 caracteres',
      email_required: 'El correo electrónico es obligatorio',
      password_required: 'La contraseña es obligatoria',
      passwords_must_match: 'Las contraseñas deben coincidir',
      confirm_password_required: 'Se requiere confirmar la contraseña',
      favorites_list_title: 'Aquí tienes tu lista de bicicletas favoritas',
      no_favorites_title: 'Aún no has guardado ningún producto en favoritos',
      no_favorites_message:
        'Parece que aún no tienes bicicletas o productos en tu lista de favoritos. ¡Empieza a explorar y guarda tus opciones favoritas para acceder a ellas fácilmente en cualquier momento!',
      back_to_home: 'Volver al inicio',
      per_day: '/día',
      day: 'día',
      days: 'días',
      bicycle_insurance: 'Seguro de bicicletas',
      VAT_included: 'Iva incluido',
      service_fee: 'Cuota de servicio',
      your_city: 'Tu ciudad',
      dates: 'Fechas',
      choose_price: 'Elige el precio',
      choose_date: 'Elige la fecha',
      apply_filter: 'Aplicar filtro',
      show_map: 'Mostrar mapa',
      show_list: 'Mostrar lista',
      calendarData: {
        monthNames: [
          'Enero',
          'Febrero',
          'Marzo',
          'Abril',
          'Mayo',
          'Junio',
          'Julio',
          'Agosto',
          'Septiembre',
          'Octubre',
          'Noviembre',
          'Diciembre',
        ],
        monthNamesShort: [
          'Ene',
          'Feb',
          'Mar',
          'Abr',
          'May',
          'Jun',
          'Jul',
          'Ago',
          'Sep',
          'Oct',
          'Nov',
          'Dic',
        ],
        dayNames: [
          'Domingo',
          'Lunes',
          'Martes',
          'Miércoles',
          'Jueves',
          'Viernes',
          'Sábado',
        ],
        dayNamesShort: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
        today: 'Hoy',
      },
      steps: {
        model: 'Modelo',
        category: 'Categoria',
        direction: 'Dirección',
        photo: 'Foto',
        price: 'Precio',
        preview: 'Avance',
      },
      checkoutSteps: {
        booking: 'Reserva',
        billing: 'Facturación',
        pay: 'Pago',
        confirmation: 'Confirmación',
      },
      date_range: ['24 junio de 2024', '31 junio de 2024', '1 julio de 2024'],
      subscription_benefits: {
        1: 'Subida ilimitada de bicicletasa',
        2: 'Mayor visibilidad en la plataforma',
        3: 'Herramientas de análisis y métricas avanzadas',
        4: 'Mejor soporte y atención personalizada',
        5: 'Acceso anticipado a nuevas funciones de la app',
      },
      reservation_details: 'Datos de la reserva',
      payment_proceed: 'Proceder al pago',
      offer_bike_component: 'Ofrece tu bicicleta o componente',
      brand_value: 'Bicicleta de Montaña Pro',
      add_photo_desc: 'Añade un foto de tu bicicleta/componente.',
      set_price_desc:
        'Establece el precio diario al que deseas alquilar tu bicicleta o componente. No te preocupes por la seguridad: nosotros nos encargamos de proteger tu bicicleta frente a cualquier eventualidad durante el alquiler.',
      address_description:
        'Agrega la dirección donde se encuentra tu bicicleta/componente para alquilar.',
      select_brand_model_description:
        'Para empezar, selecciona la marca y el modelo de tu producto. Agrega una breve descripción (opcional).',
      brand: 'Marca',
      model: 'Modelo',
      bill: 'Fianza',
      price_per_day: 'Precio por día',
      price_per_day_placeholder: 'Ej. €10',
      model_value: 'Explorador X1',
      price_details: 'Detalles de precios',
      save_continue: 'Guardar y continuar',
      billing_info: 'Datos de facturación',
      size: 'Talla',
      direction: 'Dirección',
      direction_placeholder: 'Ej. calle del Pez, Madrid',
      city: 'Ciudad',
      category: 'Categoría',
      description: 'Descripción',
      messages_date: '1 MAYO 12:00',
      enter_msg_placeholder: 'Escribe tu mensaje',
      brand_placeholder: 'Ej: Specialized',
      card_num: 'Número de la tarjeta',
      card_name: 'Nombre en la tarjeta',
      expiration_date: 'Fecha de caducidad',
      payment_method: 'Método de pago',
      card: 'Tarjeta',
      model_placeholder: 'Ej: Allez 2020',
      owner: 'Dueño',
      description_placeholder: 'Agrega una breve descripción',
      following: 'Siguiente',
      bill_placeholder: 'Ej. €10',
      get_bike: 'Subir la bicicleta',
      reserve: 'Reservar',
      summary: 'Resumen',
      product_preview_desc: 'Asi se verá tu bicicleta en nuestra plataforma.',
      deposit_text:
        'Agregar una fianza es opcional, pero ten en cuenta que puede reducir las posibilidades de que tu bicicleta sea alquilada. ¡Recuerda que ya cuentas con nuestro seguro para mayor tranquilidad!',
      select_category_description:
        'Selecciona la categoría de tu bicicleta. Si es un componente selecciona la categoría "Componente".',
      about_me: 'Sobre mi',
      configuration: 'Configuración',
      my_garage: 'Mi garaje:',
      promote: 'Promocionar',
      edit_bike: 'Editar tu bicicleta',
      keep: 'Guardar',
      account: 'Cuenta',
      my_reservations_client: 'Mis reservas como cliente',
      my_reservations_owner: 'Mis reservas como propietario',
      my_featured_bikes: 'Mis bicicletas destacadas',
      subscriptions: 'Suscripciones',
      configuration: 'Configuración',
      my_documents: 'Mis documentos',
      payment_preferences: 'Preferencias de cobro',
      edit_personal_data: 'Editar datos personales',
      edit_password: 'Editar contraseña',
      delete_account: 'Eliminar cuenta',
      sign_out: 'Cerrar sesión',
      report_incident: 'Informar incidente',
      upcoming: 'Futuras',
      in_progress: 'En curso',
      past: 'Pasadas',
      reservations: 'Reservas',
      collect: 'Recoger',
      return: 'Devolver',
      returned: 'Devuelta',
      re_book: '¿Volver a reservar?',
      reservations_owner: 'Reservas como propietario',
      earrings: 'Pendientes',
      confirmed: 'Confimadas',
      record: 'Historial',
      confirm: 'Confirmar',
      decline: 'Rechazar',
      featured_bikes: 'Mis bicicletas destacadas',
      highlight_bikes_to_increase_reservations:
        'Destaca tus bicicletas para atraer más clientes y aumentar tus reservas',
      no_bikes_msg:
        '¡Ups! No tienes ninguna bicicleta destacada en este momento. Destacar tu anuncio te asegura una posición privilegiada, apareciendo por encima de los demás.',
      no_bikes_reminder:
        'Recuerda: destacar tu bicicleta aumenta su visibilidad en la app y mejora las posibilidades de que sea reservada más rápido.',
      highlight_bicycle: 'Destacar una bicicleta',
      choose_bike: 'Elige una de tus bicicletas',
      choose_promo: 'Elige una de las promos',
      bike_highlight_label: 'Tu bici se destacará en el top durante:',
      weekend_customer_label:
        'Ideal para atraer clientes durante el fin de semana.',
      weekly_visibility_label:
        'Perfecto para maximizar tu visibilidad toda la semana.',
      limited_promotion: '¡Promoción limitada!',
      start_promotion: 'Comenzar promoción',
      my_subscriptions: 'Mis suscripciones',
      subscription_pro: 'Suscripción PRO',
      subscribe: 'Suscribirme',
      upload_front_id_msg:
        'Sube la parte delantera de tu documentos de identidad',
      upload_back_id_msg: 'Sube la parte trasera de tu documentos de identidad',
      setup_account: 'Configurar mi cuenta',
      Terms_and_conditions: 'Términos y condiciones',
      payment_placeholder: 'Register your payment method to receive income',
      bike_rental_message:
        '¡Enhorabuena! Estás a punto de ofrecer tu primera bicicleta. Para recibir los pagos por los alquileres de tu bicicleta, es necesario vincular una cuenta bancaria o tarjeta. Gestionamos esta configuración a través de Stripe, una plataforma segura y confiable. Haz clic en el botón de abajo para registrar tu cuenta y garantizar que puedas cobrar tus alquileres sin complicaciones.',
      Personal_data: 'Datos personales',
      your_name: 'Tu nombre',
      current_pass: 'Tu contraseña actual',
      new_pass: 'Tu nueva contrasña',
      del_confirm_title: '¿Estás segur@ de que deseas eliminar tu cuenta?',
      del_confirm_msg: `Eliminar tu cuenta de Bikewave es una acción irreversible. Esto significa que perderás todo tu historial de alquileres, configuraciones de perfil y cualquier dato asociado a tu cuenta.${'\n'}Si decides continuar:${'\n'}Tu cuenta será eliminada permanentemente.No podrás recuperar tu información ni acceder a tus datos nuevamente`,
      eliminate: 'Eliminar',
      success_profile_del: '¡Cuenta eliminada!',
      profile_del_msg:
        'Lamentamos verte ir, pero tu cuenta ha sido eliminada de manera permanente. Si alguna vez decides regresar, estaremos aquí para darte la bienvenida nuevamente.',
      profile_del_fail_msg:
        'Parece que hubo un problema al procesar tu petición. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      language_switch: 'Cambio de idioma',
      reserved_by: 'Reservado por:',
      confirm_email_required: 'Se requiere confirmar el correo electrónico',
      emails_must_match: 'Los correos electrónicos deben coincidir',
      forgot_password_fail:
        'No se pudo restablecer la contraseña. Intenta nuevamente',
      login_success: '¡Inicio de sesión exitoso!',
      login_success_msg:
        'Has iniciado sesión correctamente. Ahora puedes acceder a todas las funciones de la aplicación.',
      no_bicycles_found_for_this_category:
        'No se encontraron bicicletas para esta categoría',
      start_date: 'Fecha inicio',
      end_date: 'Fecha fin',
      apply: 'Aplicar',
      cancel: 'Cancelar',
      select_date_range: 'Seleccionar rango de fechas',
      edit: 'Editar',
      delete: 'Borrar',
      no_bikes_available: 'Sube tu primera bicicleta',
      confirm_delete: 'Confirmar eliminación',
      delete_warning:
        '¿Estás seguro de que quieres eliminar este artículo? Esta acción no se puede deshacer.',
      eliminate_bike: 'Eliminar la bibicleta',
      del_bike_title: '¿Estás segura de que quieres eliminar tu bicicleta?',
      del_bike_msg: `Eliminar esta bicicleta de Bikewave es una acción irreversible. Esto significa que ya no estará disponible para alquiler y se eliminarán todos los detalles asociados a este anuncio. ${'\n'}Si decides continuar:${'\n'}Tu bicicleta será eliminada permanentemente de tu perfil. No podrás recuperar la información de este anuncio ni su historial de alquileres.`,
      Brand: "Marca",
      account_completed: 'Cuenta completada',
      account_pending: 'Cuenta pendiente',
      no_account_setup: 'No hay cuenta configurada',
      no_bookings: "No hay reservas disponibles",
      check_our_bikes: "Ver nuestras bicicletas",
      validation: {
        brand_required: "La marca es obligatoria",
        model_required: "El modelo es obligatorio",
        category_required: "Por favor seleccione una categoría",
        direction_required: "Por favor seleccione una ubicación",
        photo_required: "Por favor agregue al menos una foto",
        price_required: "El precio es obligatorio",
        price_invalid: "Por favor ingrese un precio válido",
        price_positive: "El precio debe ser mayor que 0",
        deposit_required: "El depósito es obligatorio",
        deposit_invalid: "Por favor ingrese un depósito válido",
        deposit_positive: "El depósito debe ser mayor que 0"
      },
      upload_bike_success: "¡Producto subido!",
      upload_bike_success_msg: "Tu bicicleta está lista para alquilar!\nGracias por subir tu bicicleta a Bikewave. Ahora está disponible para que otros usuarios la vean y la alquilen.",
      something_went_wrong: "¡Algo salió mal!",
      upload_bike_fail_msg: "Parece que hubo un problema al subir tu producto. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.",
      back_to_home: "Volver al inicio",
      your_account_id_is: 'Su ID de cuenta es',
      required_field: 'Este campo es obligatorio',
      invalid_phone: 'Número de teléfono no válido',
      invalid_zip: 'Código postal no válido',
      accept_terms_error: 'Debes aceptar los términos y condiciones',
      validation_error: 'Error de validación',
      please_fill_required_fields: 'Por favor, complete todos los campos requeridos',
      error: 'Error',
      ok: 'Aceptar',
      chat: 'Chat',
      no_chats_available: 'No hay chats disponibles',
      your_conversations_will_appear: 'Tus conversaciones aparecerán aquí',
      errors: {
        payment_info_missing: 'Falta información de pago',
        booking_id_missing: 'Falta ID de reserva',
        payment_failed: 'Error en el pago: {{message}}',
        booking_confirmation_failed: 'Error al confirmar la reserva',
        paypal_not_implemented: 'El pago con PayPal estará disponible pronto',
        something_went_wrong: 'Algo salió mal',
        booking_fail_msg: 'Error al procesar tu reserva'
      },
      notifications: {
        new_booking_title: 'Nueva Reserva Confirmada',
        new_booking_message: 'Un usuario ha confirmado su reserva para tu bicicleta',
        booking_confirmed: 'Reserva Confirmada',
        booking_confirmed_message: 'Tu reserva ha sido confirmada por el propietario',
        booking_declined: 'Reserva Declinada',
        booking_declined_message: 'Tu solicitud de reserva ha sido rechazada por el propietario'
      },
      approval_required: 'Aprobación Requerida',
      approval_required_msg: 'Para publicar una bicicleta, primero debes ser aprobado. Por favor, sube tus documentos para la verificación.',
      upload_documents: 'Subir Documentos',
      payment_setup_required: 'Se requiere configuración de pago para recibir pagos. Por favor, configure sus preferencias de pago primero.',
      payment_setup_msg: 'Se requiere configuración de pago',
      setup_now: 'Configurar ahora',
      complete_setup: 'Completar configuración',
      stripe_capabilities_required: 'Se requieren capacidades adicionales de Stripe para recibir pagos. Por favor, complete la configuración de su cuenta de Stripe.',
      active_subscription: 'Suscripción activa',
      premium_features_enabled: 'Funciones premium habilitadas',
      my_subscriptions: 'Mis suscripciones',
      premium_member: 'Miembro Premium',
    },
  },
  {
    locale: 'en',
    translation: {
      chat: 'Chat',
      make_first_reservation: "Make your first reservation",
      home: 'Home',
      payment_details: 'Payment details',
      no_messages_yet:'No messages yet',
      checking_subscription: 'Checking subscription...',
      confirm_reservation: 'Confirm the reservation',
      favorites: 'Favorites',
      offer: 'Offer',
      messages: 'Messages',
      profile: 'Profile',
      create_your_account: 'Create your account',
      first_name: 'First Name',
      street_and_number: 'Street and number',
      street_number_placeholder: 'fish street',
      door: 'Door',
      door_placeholder: '1A',
      zip_code: 'Zip Code',
      country: 'Country',
      country_placeholder: 'Spain',
      email_placeholder: 'email@email.com',
      telephone: 'Telephone',
      accept_terms: 'I accept the',
      privacy_policy: 'Privacy Policy',
      last_name: 'Last Name',
      your_first_name: 'your first name',
      your_last_name: 'Your last name',
      email: 'Email',
      your_email: 'Your email',
      password: 'Password',
      register: 'Register',
      already_have_an_account: 'Do you already have an account?',
      dont_have_an_account: "Don't have an account?",
      login: 'Login',
      successful_registration: 'Successful registration!',
      register_success_msg:
        'Your account has been created successfully. Now you can explore and enjoy all the features our app has to offer.',
      back_to_top: 'Back to top',
      something_went_wrong: 'Something went wrong!',
      forget_password_msg:
        "Forgot your password? Don't worry, we'll help you reset it. Enter the email address associated with your account and we'll send you a link to create a new password.",
      register_fail_msg:
        'It seems there was a problem processing your registration. Please try again or contact support if the problem persists.',
      forget_password: 'I have forgotten my password',
      sign_up: 'Sign up',
      recover_password: 'Recover password',
      login_fail_msg:
        'It seems there was a problem logging in. Please try again or contact support if the problem persists.',
      repeat_email: 'Repeat your email',
      send_reset_link: 'Send reset link',
      mail_sent: 'Mail sent!',
      link_sent_msg:
        'We have sent a password reset link to your email. Please check your inbox and follow the instructions to create a new password.',
      reset_password: 'Reset password',
      new_password: 'New password',
      repeat_password: 'Repeat the new password',
      save_password: 'Save password',
      password_reset: 'Password reset!',
      booking_save: 'Reserved product!',
      booking_success_msg:
        'Your reservation has been completed successfully. The owner will confirm your request as soon as possible. We have sent you an email with all the details.',
      booking_fail_msg:
        'It seems there was a problem reserving the product. Please try again or contact support if the problem persists.',
      password_save_msg:
        'Your new password has been saved successfully. You can now use your new password to log in to your account.',
      password_save_fail_msg:
        'It seems there was a problem saving your password. Please try again or contact support if the problem persists.',
      first_name_required: 'First name is required',
      last_name_required: 'Last name is required',
      invalid_email: 'Invalid email address',
      password_min_length: 'Password must be at least 6 characters',
      email_required: 'Email is required',
      password_required: 'Password is required',
      passwords_must_match: 'Passwords must match',
      confirm_password_required: 'Confirm password is required',
      favorites_list_title: 'Here is your list of favorite bicycles',
      no_favorites_title: "You haven't saved any products to favorites yet",
      no_favorites_message:
        "It seems you don't have any bicycles or products in your favorites list yet. Start exploring and save your favorite options to access them easily at any time!",
      back_to_home: 'Back to home',
      per_day: '/day',
      day: 'day',
      days: 'days',
      bicycle_insurance: 'Bicycle Insurance',
      VAT_included: 'VAT included',
      service_fee: 'Service fee',
      your_city: 'Your City',
      dates: 'Dates',
      choose_price: 'Choose the price',
      choose_date: 'Choose the date',
      apply_filter: 'Apply filter',
      show_map: 'Show Map',
      show_list: 'Show List',
      calendarData: {
        monthNames: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December',
        ],
        monthNamesShort: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        dayNames: [
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
        ],
        dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        today: 'Today',
      },
      steps: {
        model: 'Model',
        category: 'Category',
        direction: 'Direction',
        photo: 'Photo',
        price: 'Price',
        preview: 'Preview',
      },
      checkoutSteps: {
        booking: 'Booking',
        billing: 'Billing',
        pay: 'Pay',
        confirmation: 'Confirmation',
      },
      date_range: [
        'June 24 from 2024',
        'June 31 from 2024',
        'July 1 from 2024',
      ],
      subscription_benefits: {
        1: 'Unlimited bike upload',
        2: 'Greater visibility on the platform',
        3: 'Advanced metrics and analysis tools',
        4: 'Better support and personalized attention',
        5: 'Early access to new app features',
      },
      reservation_details: 'Reservation details',
      payment_proceed: 'Proceed to payment',
      offer_bike_component: 'Offer your bicycle or component',
      brand_value: 'Mountain Bike Pro',
      add_photo_desc: 'Add a photo of your bike/component.',
      set_price_desc:
        "Set the daily price at which you want to rent your bike or component. Don't worry about security: we will take care of protecting your bicycle against any eventuality during the rental.",
      address_description:
        'Add the address where your bike/component is for rent.',
      select_brand_model_description:
        'To get started, select the brand and the model of your product. Add a brief description (optional).',
      brand: 'Brand',
      model: 'Model',
      bill: 'Bill',
      price_per_day: 'Price per day',
      price_per_day_placeholder: 'Ex. €10',
      model_value: 'Explorer X1',
      price_details: 'Pricing details',
      save_continue: 'Save and continue',
      billing_info: 'Billing information',
      size: 'Size',
      direction: 'Direction',
      direction_placeholder: 'Calle del Pez, Madrid',
      city: 'City',
      category: 'Category',
      description: 'Description',
      messages_date: '1 MARCH 12:00',
      enter_msg_placeholder: 'Write your message',
      brand_placeholder: 'Ex: Specialized',
      card_num: 'Card Number',
      card_name: 'Name on Card',
      expiration_date: 'Expiration date',
      payment_method: 'Payment method',
      card: 'Card',
      model_placeholder: 'Ex: Allez 2020',
      owner: 'Owner',
      description_placeholder: 'Add a short description',
      following: 'Following',
      bill_placeholder: 'Ex. €10',
      get_bike: 'Get on the bike',
      reserve: 'Reserve',
      summary: 'Summary',
      product_preview_desc: 'This is how your bike will look on our platform.',
      deposit_text:
        'Adding a deposit is optional, but keep in mind that it may reduce the chances of your bike being rented. Remember that you already have our insurance for greater peace of mind!',
      select_category_description:
        'Select the category of your bicycle. If it is a component, select the "Component" category.',
      about_me: 'About me',
      configuration: 'Configuration',
      my_garage: 'My garage:',
      promote: 'Promote',
      edit_bike: 'Edit your Bike',
      keep: 'Keep',
      account: 'Account',
      my_reservations_client: 'My reservations as client',
      my_reservations_owner: 'My reservations as owner',
      my_featured_bikes: 'My featured bicycles',
      subscriptions: 'Subscriptions',
      configuration: 'Configuration',
      my_documents: 'My documents',
      payment_preferences: 'Payment preferences',
      edit_personal_data: 'Edit personal data',
      edit_password: 'Edit password',
      delete_account: 'Delete account',
      sign_out: 'Sign out',
      report_incident: 'Report incident',
      upcoming: 'Upcoming',
      in_progress: 'In Progress',
      past: 'Past',
      reservations: 'Reservations',
      collect: 'Collect',
      return: 'Return',
      returned: 'Returned',
      re_book: 'Rebook?',
      reservations_owner: 'Reservations as owner',
      earrings: 'Earrings',
      confirmed: 'Confirmed',
      record: 'Record',
      confirm: 'Confirm',
      decline: 'Decline',
      featured_bikes: 'My featured bikes',
      highlight_bikes_to_increase_reservations:
        'Highlight your bikes to attract more customers and increase your reservations',
      no_bikes_msg: `Oops! You don't have any featured bikes at the moment. Highlighting your ad ensures you a privileged position, appearing above the others.`,
      no_bikes_reminder:
        'Remember: highlighting your bike increases its visibility in the app and improves the chances of it being booked faster.',
      highlight_bicycle: 'Highlight a bicycle',
      choose_bike: 'Choose one of your bikes',
      choose_promo: 'Choose one of the promos',
      bike_highlight_label: 'Your bike will stand out at the top during:',
      weekend_customer_label: 'Ideal to attract customers during the weekend.',
      weekly_visibility_label: 'Perfect to maximize your visibility all week.',
      limited_promotion: 'Limited promotion!',
      start_promotion: 'Start promotion',
      my_subscriptions: 'My subscriptions',
      subscription_pro: 'PRO Subscription',
      subscribe: 'Subscribe',
      upload_front_id_msg: 'Upload the front of your ID documents',
      upload_back_id_msg: 'Upload the back of your ID documents',
      setup_account: 'Set up my account',
      Terms_and_conditions: 'Terms and conditions',
      payment_placeholder: 'Register your payment method to receive income',
      bike_rental_message:
        'Congratulations! You are about to offer your first bicycle. To receive payments for your bike rentals, you need to link a bank account or card. We manage this setup through Stripe, a secure and reliable platform. Click the button below to register your account and ensure you can collect your rents without complications.',
      Personal_data: 'Personal data',
      your_name: 'your name',
      current_pass: 'Your current password',
      new_pass: 'Your new password',
      del_confirm_title: 'Are you sure you want to delete your account?',
      del_confirm_msg: `Deleting your Bikewave account is an irreversible action. This means you will lose all of your rental history, profile settings, and any data associated with your account.${'\n'}If you decide to continue:${'\n'}Your account will be permanently deleted.You will not be able to recover your information or access your data again`,
      eliminate: 'Eliminate',
      success_profile_del: 'Account deleted!',
      profile_del_msg: `We're sorry to see you go, but your account has been permanently deleted. If you ever decide to return, we will be here to welcome you again.`,
      profile_del_fail_msg:
        'It appears there was a problem processing your request. Please try again or contact support if the problem persists.',
      language_switch: 'Language Switch',
      reserved_by: 'Reserved By:',
      confirm_email_required: 'Email confirmation is required',
      emails_must_match: 'Emails must match',
      forgot_password_fail: 'Password reset failed. Please try again',
      login_success: 'Login successful!',
      login_success_msg:
        'You have successfully logged in. You can now access all the features of the app.',
      no_bicycles_found_for_this_category:
        'No bicycles found for this category',
      start_date: 'Start Date',
      end_date: 'End Date',
      apply: 'Apply',
      cancel: 'Cancel',
      select_date_range: 'Select Booking Dates',
      edit: 'Edit',
      delete: 'Delete',
      no_bikes_available: 'Upload your first bicycle',
      confirm_delete: 'Confirm Delete',
      delete_warning:
        'Are you sure you want to delete this item? This action cannot be undone.',
      eliminate_bike: 'Eliminate the bicycle',
      del_bike_title: 'Are you sure you want to delete your bicycle?',
      del_bike_msg: `Deleting this bike from Bikewave is an irreversible action. This means it will no longer be available for rental and all details associated with this listing will be removed. ${'\n'}If you decide to continue:${'\n'}Your bike will be permanently removed from your profile. You will not be able to recover the information from this ad or its rental history.`,
      Brand: "Brand",
      account_completed: 'Account completed',
      account_pending: 'Account pending',
      no_account_setup: 'No account setup',
      no_bookings: "No bookings available",
      check_our_bikes: "Check our bikes",
      validation: {
        brand_required: "Brand is required",
        model_required: "Model is required",
        category_required: "Please select a category",
        photo_required: "Please add at least one photo",
        direction_required: "Please select a location",
        price_required: "Price is required",
        price_invalid: "Please enter a valid price",
        price_positive: "Price must be greater than 0",
        deposit_required: "Deposit amount is required",
        deposit_invalid: "Please enter a valid deposit amount",
        deposit_positive: "Deposit must be greater than 0"
      },
      upload_bike_success: "Product Uploaded!",
      upload_bike_success_msg: "Your bike is ready to rent!\nThank you for uploading your bike to Bikewave. It's now available for other users to view and rent.",
      something_went_wrong: "Something went wrong!",
      upload_bike_fail_msg: "There seems to be a problem uploading your product. Please try again or contact support if the problem persists.",
      back_to_home: "Back to Home",
      your_account_id_is: 'Your account ID is',
      required_field: 'This field is required',
      invalid_phone: 'Invalid phone number',
      invalid_zip: 'Invalid ZIP code',
      accept_terms_error: 'You must accept the terms and conditions',
      validation_error: 'Validation Error',
      please_fill_required_fields: 'Please fill in all required fields',
      error: 'Error',
      ok: 'OK',
      no_chats_available: 'No Chats Available',
      your_conversations_will_appear: 'Your conversations will appear here',
      errors: {
        payment_info_missing: 'Payment information is missing',
        booking_id_missing: 'Booking ID is missing',
        payment_failed: 'Payment failed: {{message}}',
        booking_confirmation_failed: 'Failed to confirm booking',
        paypal_not_implemented: 'PayPal payment will be implemented soon',
        something_went_wrong: 'Something went wrong',
        booking_fail_msg: 'Failed to process your booking'
      },
      notifications: {
        new_booking_title: 'New Booking Confirmed',
        new_booking_message: 'A user has confirmed their booking for your bike',
        booking_confirmed: 'Booking Confirmed',
        booking_confirmed_message: 'Your booking has been confirmed by the owner',
        booking_declined: 'Booking Declined',
        booking_declined_message: 'Your booking request has been declined by the owner'
      },
      approval_required: 'Approval Required',
      approval_required_msg: 'To post a bike, you need to be approved first. Please upload your documents for verification.',
      upload_documents: 'Upload Documents',
      payment_setup_required: 'Payment setup is required to receive payments. Please set up your payment preferences first.',
      payment_setup_msg: 'Payment setup required',
      setup_now: 'Setup Now',
      complete_setup: 'Complete Setup',
      stripe_capabilities_required: 'Additional Stripe capabilities are required to receive payments. Please complete your Stripe account setup.',
      active_subscription: 'Active subscription',
      premium_features_enabled: 'Premium features enabled',
      my_subscriptions: 'My subscriptions',
      premium_member: 'Premium member',
    },
  },
];

export const appLanguages = [
  {
    id: '0',
    name: 'Spanish',
    code: 'sp',
  },
  {
    id: '1',
    name: 'English',
    code: 'en',
  },
];
